### ISSUE TITLE
IndexError: list index out of range


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#646]
```
2024-02-25 06:07:53 = ERROR = sys_stream = Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/graphs/get_elections_graphs.py", line 40, in get_elections_graphs
    position = nominee_positions[indx].position_name
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/models/query.py", line 309, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/graphs/get_elections_graphs.py", line 40, in get_elections_graphs
    position = nominee_positions[indx].position_name
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/models/query.py", line 309, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/csss-site/commit/7a3c26388d457d8a8ba9ea459a05fb390249c94f
