### ISSUE TITLE
cmd_validate_google_workspace_shared_team_drive_for_public_gallery = [Errno 32] Broken pipe


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#647]
```
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = Traceback (most recent call last):

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "manage.py", line 22, in <module>

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = execute_from_command_line(sys.argv)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = utility.execute()
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self.fetch_command(subcommand).run_from_argv(self.argv)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self.execute(*args, **cmd_options)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = output = self.handle(*args, **options)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/management/commands/validate_google_workspace_shared_team_drive_for_public_gallery.py", line 17, in handle

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = validate_google_workspace_shared_team_drive_for_public_gallery()
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_views.py", line 129, in validate_google_workspace_shared_team_drive_for_public_gallery

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = GoogleDrive(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 369, in validate_ownerships_and_permissions

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self._validate_individual_file_and_folder_ownership_and_permissions("CSSS", google_drive_perms)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 512, in _validate_individual_file_and_folder_ownership_and_permissions

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = files_to_email_owner_about = self._validate_owner_for_file(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 754, in _validate_owner_for_file

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = return self._validate_individual_file_and_folder_ownership_and_permissions(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 512, in _validate_individual_file_and_folder_ownership_and_permissions

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = files_to_email_owner_about = self._validate_owner_for_file(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 754, in _validate_owner_for_file

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = return self._validate_individual_file_and_folder_ownership_and_permissions(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 512, in _validate_individual_file_and_folder_ownership_and_permissions

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = files_to_email_owner_about = self._validate_owner_for_file(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 754, in _validate_owner_for_file

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = return self._validate_individual_file_and_folder_ownership_and_permissions(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 509, in _validate_individual_file_and_folder_ownership_and_permissions

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self._validate_permissions_for_file(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/csss-site/resource_management/views/resource_apis/gdrive/gdrive_api.py", line 605, in _validate_permissions_for_file

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = file_permissions_executor = getter.execute()
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = return wrapped(*args, **kwargs)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/googleapiclient/http.py", line 844, in execute

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = resp, content = _retry_request(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/googleapiclient/http.py", line 183, in _retry_request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = raise exception
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/googleapiclient/http.py", line 164, in _retry_request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = resp, content = http.request(uri, method, *args, **kwargs)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/google_auth_httplib2.py", line 186, in request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self.credentials.before_request(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/google/auth/credentials.py", line 133, in before_request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self.refresh(request)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/google/oauth2/credentials.py", line 228, in refresh

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = ) = reauth.refresh_grant(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/google/oauth2/reauth.py", line 318, in refresh_grant

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = response_status_ok, response_data = _client._token_endpoint_request_no_throw(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/google/oauth2/_client.py", line 115, in _token_endpoint_request_no_throw

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = response = request(method="POST", url=token_uri, headers=headers, body=body)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/google_auth_httplib2.py", line 115, in __call__

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = response, data = self.http.request(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/httplib2/__init__.py", line 1708, in request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = (response, content) = self._request(
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/httplib2/__init__.py", line 1424, in _request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = (response, content) = self._conn_request(conn, request_uri, method, body, headers)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/home/csss/envCSSS/lib/python3.8/site-packages/httplib2/__init__.py", line 1347, in _conn_request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = conn.request(method, request_uri, body, headers)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/usr/lib/python3.8/http/client.py", line 1256, in request

2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self._send_request(method, url, body, headers, encode_chunked)
2024-02-27 04:59:23 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request

2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self.endheaders(body, encode_chunked=encode_chunked)
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders

2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self._send_output(message_body, encode_chunked=encode_chunked)
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/usr/lib/python3.8/http/client.py", line 1050, in _send_output

2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self.send(chunk)
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/usr/lib/python3.8/http/client.py", line 972, in send

2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = self.sock.sendall(data)
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/usr/lib/python3.8/ssl.py", line 1204, in sendall

2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = v = self.send(byte_view[count:])
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =   File "/usr/lib/python3.8/ssl.py", line 1173, in send

2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery =     
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = return self._sslobj.write(data)
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = BrokenPipeError
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = : 
2024-02-27 04:59:24 = ERROR = cmd_validate_google_workspace_shared_team_drive_for_public_gallery = [Errno 32] Broken pipe

```

**Comment by modernNeo** [comment]
dealt with with https://github.com/CSSS/csss-site/commit/26c150787c4cec3fb753674d31cdd2dd45858b48
