### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sfuid'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#648]
```
2024-02-27 21:18:30 = ERROR = sys_stream = Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/nominee_links/display_and_process_html_for_nominee_modification__nominee_link.py", line 36, in display_and_process_html_for_nominee_modification
    create_context_for_create_or_update_nominee__nominee_links_html(
  File "/home/csss/csss-site/elections/views/create_context/nominee_links/create_or_update_nominee/create_context_for_create_or_update_nominee__nominee_links_html.py", line 54, in create_context_for_create_or_update_nominee__nominee_links_html
    election_officer_request=election_officer_request, sfuid=nominee_link.sfuid
AttributeError: 'NoneType' object has no attribute 'sfuid'
Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/nominee_links/display_and_process_html_for_nominee_modification__nominee_link.py", line 36, in display_and_process_html_for_nominee_modification
    create_context_for_create_or_update_nominee__nominee_links_html(
  File "/home/csss/csss-site/elections/views/create_context/nominee_links/create_or_update_nominee/create_context_for_create_or_update_nominee__nominee_links_html.py", line 54, in create_context_for_create_or_update_nominee__nominee_links_html
    election_officer_request=election_officer_request, sfuid=nominee_link.sfuid
AttributeError: 'NoneType' object has no attribute 'sfuid'

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/csss-site/commit/febdbe3080951334df78d479a3ae12e737c7834f
