### ISSUE TITLE
	before or while processing the request.


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#649]
```
2024-02-29 12:14:57 = ERROR = cmd_cron_service = Traceback (most recent call last):

2024-02-29 12:14:57 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = return self.cursor.execute(sql, params)
2024-02-29 12:14:58 = ERROR = cmd_cron_service = psycopg2.errors
2024-02-29 12:14:58 = ERROR = cmd_cron_service = .
2024-02-29 12:14:58 = ERROR = cmd_cron_service = AdminShutdown
2024-02-29 12:14:58 = ERROR = cmd_cron_service = : 
2024-02-29 12:14:58 = ERROR = cmd_cron_service = terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2024-02-29 12:14:58 = ERROR = cmd_cron_service = 
The above exception was the direct cause of the following exception:


2024-02-29 12:14:58 = ERROR = cmd_cron_service = Traceback (most recent call last):

2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "manage.py", line 22, in <module>

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = execute_from_command_line(sys.argv)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = utility.execute()
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = self.fetch_command(subcommand).run_from_argv(self.argv)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = self.execute(*args, **cmd_options)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = output = self.handle(*args, **options)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/csss-site/csss/management/commands/cron_service.py", line 45, in handle

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = for updated_cron_job in updated_cron_jobs:
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = self._fetch_all()
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = self._result_cache = list(self._iterable_class(self))
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = cursor.execute(sql, params)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = return executor(sql, params, many, context)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = return self.cursor.execute(sql, params)
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = raise dj_exc_value.with_traceback(traceback) from exc_value
2024-02-29 12:14:58 = ERROR = cmd_cron_service =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute

2024-02-29 12:14:58 = ERROR = cmd_cron_service =     
2024-02-29 12:14:58 = ERROR = cmd_cron_service = return self.cursor.execute(sql, params)
2024-02-29 12:14:58 = ERROR = cmd_cron_service = django.db.utils
2024-02-29 12:14:58 = ERROR = cmd_cron_service = .
2024-02-29 12:14:58 = ERROR = cmd_cron_service = OperationalError
2024-02-29 12:14:58 = ERROR = cmd_cron_service = : 
2024-02-29 12:14:58 = ERROR = cmd_cron_service = terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


```

**Comment by modernNeo** [comment]
idk what happened but I am guessing it was a 1 time issue
