### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#652]
```
2024-03-16 08:44:27 = ERROR = sys_stream = Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/nominee_links/display_and_process_html_for_nominee_modification_via_passphrase__nominee_link.py", line 40, in display_and_process_html_for_nominee_modification_via_passphrase
    return process_nominee__nominee_links(
  File "/home/csss/csss-site/elections/views/update_election/nominee_links/process_nominee__nominee_links.py", line 85, in process_nominee__nominee_links
    save_new_nominee_jformat(
  File "/home/csss/csss-site/elections/views/save_nominee/save_new_nominee_jformat.py", line 43, in save_new_nominee_jformat
    discord_id = discord_id.strip() if facebook_link is not None else None
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/nominee_links/display_and_process_html_for_nominee_modification_via_passphrase__nominee_link.py", line 40, in display_and_process_html_for_nominee_modification_via_passphrase
    return process_nominee__nominee_links(
  File "/home/csss/csss-site/elections/views/update_election/nominee_links/process_nominee__nominee_links.py", line 85, in process_nominee__nominee_links
    save_new_nominee_jformat(
  File "/home/csss/csss-site/elections/views/save_nominee/save_new_nominee_jformat.py", line 43, in save_new_nominee_jformat
    discord_id = discord_id.strip() if facebook_link is not None else None
AttributeError: 'NoneType' object has no attribute 'strip'

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/csss-site/commit/534a42c68664bba224ec40396b3870c3738055d0
