### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'pstdatetime'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#654]
```
2024-03-16 21:48:39 = ERROR = sys_stream = Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/graphs/get_elections_graphs.py", line 33, in get_elections_graphs
    if election.end_date > today_date and results_detected:
TypeError: '>' not supported between instances of 'NoneType' and 'pstdatetime'
Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/elections/views/endpoints/graphs/get_elections_graphs.py", line 33, in get_elections_graphs
    if election.end_date > today_date and results_detected:
TypeError: '>' not supported between instances of 'NoneType' and 'pstdatetime'

```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/csss-site/commit/38949752511159d66a3ffdba7c505d2432643a08
