### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: './about/cron_scripts/prod_nag_doa_to_generate_links.sh'


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#658]
```
2024-03-24 09:00:00 = ERROR = cmd_cron_service = Job "run_job (trigger: cron[month='*', day='*', day_of_week='*', hour='9', minute='0'], next run at: 2024-03-25 09:00:00 PDT)" raised an exception
Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/csss/csss-site/about/views/cron_jobs/nag_doa_to_generate_links.py", line 12, in run_job
    process = Popen(['./about/cron_scripts/prod_nag_doa_to_generate_links.sh'])
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './about/cron_scripts/prod_nag_doa_to_generate_links.sh'


```

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/csss-site/commit/0afdddb5142cc68d50e09321a97cc89050f5cf97
