### ISSUE TITLE
django_cas_ng.utils.RedirectException: Non-local url is forbidden to be redirected to.


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#668]
```
2024-04-17 17:25:06 = ERROR = sys_stream = Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django_cas_ng/views.py", line 72, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/csss/csss-site/csss/views/login.py", line 58, in get
    return super().get(request)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django_cas_ng/views.py", line 103, in get
    next_page = clean_next_page(request, request.GET.get('next'))
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django_cas_ng/views.py", line 45, in clean_next_page
    raise RedirectException("Non-local url is forbidden to be redirected to.")
django_cas_ng.utils.RedirectException: Non-local url is forbidden to be redirected to.
Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django_cas_ng/views.py", line 72, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/csss/csss-site/csss/views/login.py", line 58, in get
    return super().get(request)
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django_cas_ng/views.py", line 103, in get
    next_page = clean_next_page(request, request.GET.get('next'))
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django_cas_ng/views.py", line 45, in clean_next_page
    raise RedirectException("Non-local url is forbidden to be redirected to.")
django_cas_ng.utils.RedirectException: Non-local url is forbidden to be redirected to.

```

**Comment by modernNeo** [comment]
handled with https://github.com/CSSS/csss-site/commit/f11c429d362f6e35bde30fea6b2eb101078d4bff
