### ISSUE TITLE
cmd_validate_discord_roles_members = list indices must be integers or slices, not str


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#669]
```
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = Traceback (most recent call last):

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =   File "manage.py", line 22, in <module>

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =     
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = execute_from_command_line(sys.argv)
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =     
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = utility.execute()
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =     
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = self.fetch_command(subcommand).run_from_argv(self.argv)
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =     
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = self.execute(*args, **cmd_options)
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =   File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =     
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = output = self.handle(*args, **options)
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =   File "/home/csss/csss-site/about/management/commands/validate_discord_roles_members.py", line 102, in handle

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =     
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = determine_changes_for_exec_discord_group_role_validation(
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =   File "/home/csss/csss-site/about/views/commands/validate_discord_roles_members/determine_changes_for_exec_discord_group_role_validation.py", line 68, in determine_changes_for_exec_discord_group_role_validation

2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members =     
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = members_id__role_ids[user_that_should_be_in_discord_role]['roles'][role_name] = exec_discord_role_id
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = TypeError
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = : 
2024-04-21 05:40:14 = ERROR = cmd_validate_discord_roles_members = list indices must be integers or slices, not str

```

**Comment by modernNeo** [comment]
implemented logging to figure out what is going wrong here https://github.com/CSSS/csss-site/commit/daa4890ff64316e92b9ebe89a6acd2547abb95db
