### ISSUE TITLE
django.core.exceptions.ValidationError: ['There is already an officer saved for term 20243 for officer Emily Qin and position name Director of Events under start_date 2024-04-19 00:00:00-07:00']


### ISSUE THREAD

**Issue by csss-admin** [CSSS/csss-site#694]
```
2024-08-06 07:55:59 = ERROR = sys_stream = Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/about/views/input_new_officers/enter_new_officer_info/enter_new_officer_info.py", line 26, in enter_new_officer_info
    return process_new_officer_info(
  File "/home/csss/csss-site/about/views/input_new_officers/enter_new_officer_info/process_new_officer_info.py", line 112, in process_new_officer_info
    success, error_message = save_officer_and_grant_digital_resources(
  File "/home/csss/csss-site/about/views/input_new_officers/enter_new_officer_info/save_officer_and_grant_digital_resources.py", line 189, in save_officer_and_grant_digital_resources
    officer_obj.save()
  File "/home/csss/csss-site/about/models.py", line 83, in save
    self.validate_unique()
  File "/home/csss/csss-site/about/models.py", line 77, in validate_unique
    raise ValidationError(
django.core.exceptions.ValidationError: ['There is already an officer saved for term 20243 for officer Emily Qin and position name Director of Events under start_date 2024-04-19 00:00:00-07:00']
Traceback (most recent call last):
  File "/home/csss/envCSSS/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/csss/csss-site/about/views/input_new_officers/enter_new_officer_info/enter_new_officer_info.py", line 26, in enter_new_officer_info
    return process_new_officer_info(
  File "/home/csss/csss-site/about/views/input_new_officers/enter_new_officer_info/process_new_officer_info.py", line 112, in process_new_officer_info
    success, error_message = save_officer_and_grant_digital_resources(
  File "/home/csss/csss-site/about/views/input_new_officers/enter_new_officer_info/save_officer_and_grant_digital_resources.py", line 189, in save_officer_and_grant_digital_resources
    officer_obj.save()
  File "/home/csss/csss-site/about/models.py", line 83, in save
    self.validate_unique()
  File "/home/csss/csss-site/about/models.py", line 77, in validate_unique
    raise ValidationError(
django.core.exceptions.ValidationError: ['There is already an officer saved for term 20243 for officer Emily Qin and position name Director of Events under start_date 2024-04-19 00:00:00-07:00']

```

**Comment by modernNeo** [comment]
Emily probably just did a double-click.
